### ISSUE TITLE
AnnotationRepositoryConfigurationSource.getAttribute(…) fails if attribute is not declared on annotation [DATACMNS-1169]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1610]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATACMNS-1169](https://jira.spring.io/browse/DATACMNS-1169?redirect=false)** and commented

Calling `AnnotationRepositoryConfigurationSource.getAttribute(…)` with an attribute name that does not exist on the annotation fails with `IllegalArgumentException`.

```
java.lang.IllegalArgumentException: Attribute 'keyValueMappingContextRef' not found in attributes for annotation [unknown]
	at org.springframework.util.Assert.notNull(Assert.java:210)
	at org.springframework.core.annotation.AnnotationAttributes.assertAttributePresence(AnnotationAttributes.java:350)
	at org.springframework.core.annotation.AnnotationAttributes.getRequiredAttribute(AnnotationAttributes.java:337)
	at org.springframework.core.annotation.AnnotationAttributes.getString(AnnotationAttributes.java:165)
	at org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.getAttribute(AnnotationRepositoryConfigurationSource.java:330)
```

It rather should return `Optional.empty()` or `RepositoryConfigurationSource` should provide means to query whether an attribute is available

---
No further details from [DATACMNS-1169](https://jira.spring.io/browse/DATACMNS-1169?redirect=false)

**Comment by mp911de** [comment]
Fixed via #1932
