### ISSUE TITLE
Concurrent modification exceptions thrown if multiple events are are fired/published in a multithreaded setup [DATACMNS-1183]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-commons#1625]
**[Gaurav Rawat](https://jira.spring.io/secure/ViewProfile.jspa?name=gauravbrills)** opened **[DATACMNS-1183](https://jira.spring.io/browse/DATACMNS-1183?redirect=false)** and commented

Example
Event 1 Fired on Domain ->
Event 1 captured by Listener ->
Event 2 Fired inside listener on same domain object
Alll the above taking place in a multi threaded setup ..
Exception Trace

```java
 Unexpected error occurred invoking async method 'public void com.test.broker.events.ProcessLifecycleEventListener.onFlowChange(com.test.broker.events.ProcessLifecycleEvent)'.
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at org.springframework.data.repository.core.support.EventPublishingRepositoryProxyPostProcessor$EventPublishingMethod.publishEven           tsFrom(EventPublishingRepositoryProxyPostProcessor.java:168)
        at org.springframework.data.repository.core.support.EventPublishingRepositoryProxyPostProcessor$EventPublishingMethodInterceptor.           invoke(EventPublishingRepositoryProxyPostProcessor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransaction           DetectorMethodInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy129.save(Unknown Source)
        at com.test.broker.events.ProcessLifecycleEventListener.onFlowChange(ProcessLifecycleEventListener.java:42)
        at com.test.broker.events.ProcessLifecycleEventListener$$FastClassBySpringCGLIB$$bfc85b32.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at org.springframework.cloud.sleuth.instrument.async.TraceAsyncAspect.traceBackgroundThread(TraceAsyncAspect.java:67)
        at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

```

pseudo code for the setup

```java
public class Test extends AbstractAggregateRoot
{
 private String id;
public FeedControl logEvent()
   {
      LogFeedEvent event = LogFeedEvent.builder().id(this.id).build();
 
      registerEvent(event);
      return this;
   }
 
   public FeedControl doLifeCycleChange()
   {
      ProcessLifecycleEvent event = ProcessLifecycleEvent.builder().test(this).build();
 
      registerEvent(event);
      return this;
   }
}
 
public class ProcessLifecycleEventListener
{
@Async
   @EventListener
   public void onFlowChange(ProcessLifecycleEvent event)
   {
   testRepository.save(event.getTest().logEvent()); // This fails and gives the concurrent modification exception m
}
}

```

Example test case to replicate the same is here https://github.com/gauravbrills/SpringPlayground/blob/750f6be6a1b16389be569c1b56fbc43f28f9d7bf/src/test/java/me/gauravbrills/AppIntegrationTest.java#L65  .As a quick workaround for now change the list implementation in the AbstractAggregate to a CopyOnWriteArrayList

---

**Reference URL:** https://github.com/gauravbrills/SpringPlayground/blob/750f6be6a1b16389be569c1b56fbc43f28f9d7bf/src/test/java/me/gauravbrills/AppIntegrationTest.java#L65

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
