### ISSUE TITLE
Error in Projection [DATACMNS-1343]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1779]
**[Marcos Vinicius Policarpo Côrtes](https://jira.spring.io/secure/ViewProfile.jspa?name=mvpcortes)** opened **[DATACMNS-1343](https://jira.spring.io/browse/DATACMNS-1343?redirect=false)** and commented

We have a web application that use Spring Data JPA.

 
We have a simple oracle VIEW and mapped this fields to a entity (ex):

```java
@Entity class IdCourse {
  private int idCity;
  private int idUniversity;
}
@Entity class Course {
  @EmbeddedId private IdCourse idCourse;
  private String name;
  private Integer year; 
  // ( a lot of fields) (get/set)
}
```

 

And we create a [projection](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections) using spring-data-jpa, like this:

```java
interface ProjCourse {
  @Value("#{target.name}")
  String getName();

  @Value("#{target.year}")
  Integer getYear();
}
```

then make a query in a CrudRepository like this:

```java
interface ProjCourseDAO implements CrudRepository<Course, Long> {
  @Query("SELECT DISTINCT c.name name, c.year year FROM #{#entityName} c WHERE c.idCity = ?1 AND c.idUniversity = ?2")
  List<ProjCourse> list(Long idCity, Long idUniversity);
}
```

 
We have used the code since version Spring-boot 1.15.8 (1.13.10) and it works. After update to Spring-boot 1.15.11 (1.13.13) we receive the exception:

 

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:653) at java.util.ArrayList.get(ArrayList.java:429) at org.springframework.data.repository.query.ResultProcessor$ProjectingConverter.toMap(ResultProcessor.java:310) at org.springframework.data.repository.query.ResultProcessor$ProjectingConverter.getProjectionTarget(ResultProcessor.java:298) at org.springframework.data.repository.query.ResultProcessor$ProjectingConverter.convert(ResultProcessor.java:285) at org.springframework.data.repository.query.ResultProcessor$ChainingConverter$1.convert(ResultProcessor.java:210) at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.convert(ResultProcessor.java:221) at org.springframework.data.repository.query.ResultProcessor.processResult(ResultProcessor.java:152) at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:133) at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:118) at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:494) at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:477) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) at com.sun.proxy.$Proxy147.list(Unknown Source) at br.uff.radoc.service.CourseService.listProjCoure(CourseService.java:xxx) <....> at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
```

We can help-me with this exception? I will try this weekend create a sample project with this error and try a solution...

---

**Affects:** 1.13.13 (Ingalls SR13)

**Reference URL:** https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections

1 votes, 1 watchers

**Comment by mp911de** [comment]
This issue is solved in newer Spring Data versions, tested against Spring Data 2.7.8. Also, the syntax of `${target.idStudent}` has been wrong, it should have been `#{target.id_student}`
