### ISSUE TITLE
Investigate support for JDK 14 record types in object mapping [DATACMNS-1636]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2062]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATACMNS-1636](https://jira.spring.io/browse/DATACMNS-1636?redirect=false)** and commented

---
No further details from [DATACMNS-1636](https://jira.spring.io/browse/DATACMNS-1636?redirect=false)

**Comment by sothawo** [comment]
Hello,

what's the state of this? I just tried to use a `record`as entity type in Spring Data Elasticsearch and got

```
2021-05-01 16:11:20.839 ERROR 77582 --- [nio-9090-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate com.sothawo.springdataelastictest.presidents.President using constructor NO_CONSTRUCTOR with arguments ] with root cause

java.lang.NoSuchMethodException: com.sothawo.springdataelastictest.presidents.President.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3517) ~[na:na]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.data.mapping.model.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:62) ~[spring-data-commons-2.6.0-20210427.084756-6.jar:2.6.0-SNAPSHOT]
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:89) ~[spring-data-commons-2.6.0-20210427.084756-6.jar:2.6.0-SNAPSHOT]
	at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.readEntity(MappingElasticsearchConverter.java:321) ~[spring-data-elasticsearch-4.3.0-SNAPSHOT.jar:4.3.0-SNAPSHOT]
```

using this class (`Term` is another record class):
```
@Document(indexName = "presidents")
public record President(
    @Id
    String id,

    @Field(type = FieldType.Text)
    String name,

    @Field(type = FieldType.Integer_Range)
    Term term) {
}
```

**Comment by mp911de** [comment]
Records are supported since quite a while and persistence constructor detection works as with other classes. For some reason, the entity instantiator tries to use a no-arg constructor

**Comment by sothawo** [comment]
ok, I have an additional ctor in there which I omitted above, when annotating the compact ctor it works:
```
@Document(indexName = "presidents")
public record President(
    @Id
    String id,

    @Field(type = FieldType.Text)
    String name,

    @Field(type = FieldType.Integer_Range)
    Term term) {

    @PersistenceConstructor
    public President{}

    public President(String name, Term term) {
        this(UUID.randomUUID().toString(), name, term);
    }
}
```

**Comment by indiepopart** [comment]
> Records are supported since quite a while and persistence constructor detection works as with other classes. For some reason, the entity instantiator tries to use a no-arg constructor

I can't find a note in spring-data-commons reference about records. Would you please point me to documentation where it is mentioned?

**Comment by mp911de** [comment]
Records are classes with a specific naming scheme after all and those work out of the box. However, we do recommend using records for DTO's as they are not a good fit as entities. We should use this ticket to document the recommendation.
