### ISSUE TITLE
QuerydslPredicateBuilder looks at Type properties instead of QType [DATACMNS-1760]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2176]
**[James Howe](https://jira.spring.io/secure/ViewProfile.jspa?name=jamesmhowe)** opened **[DATACMNS-1760](https://jira.spring.io/browse/DATACMNS-1760?redirect=false)** and commented

When constructing a Querydsl predicate from request parameters, the source type is inspected to determine which parameter names to use, instead of the query type.

This results in exceptions for properties that exist but are not queryable. Instead they should behave the same as properties that don't exist, and be ignored.

 

```java
@Data
@Entity
public class Example {
    private String one;

    @QueryType(PropertyType.NONE)
    private String two;

    private transient String three;
}
```

```java
@Controller
public class ExampleController {
    @RequestMapping("/")
    public void test(@QuerydslPredicate(root = Example.class) Predicate predicate) {
    }
}
```

`GET /?one=foo` -> success
`GET /?two=foo` -> error
`GET /?three=foo` -> error
`GET /?four=foo` -> success

 

```
java.lang.IllegalArgumentException: Unable to find field two on class com.example.QExample!
	at org.springframework.data.util.ReflectionUtils.findRequiredField(ReflectionUtils.java:211)
	at org.springframework.data.querydsl.binding.PropertyPathInformation.lambda$reifyPath$3(PropertyPathInformation.java:139)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.springframework.data.querydsl.binding.PropertyPathInformation.reifyPath(PropertyPathInformation.java:135)
	at org.springframework.data.querydsl.binding.PropertyPathInformation.reifyPath(PropertyPathInformation.java:125)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.lambda$null$0(QuerydslPredicateBuilder.java:153)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.lambda$getPath$1(QuerydslPredicateBuilder.java:153)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.getPath(QuerydslPredicateBuilder.java:153)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.invokeBinding(QuerydslPredicateBuilder.java:135)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.getPredicate(QuerydslPredicateBuilder.java:116)
	at org.springframework.data.web.querydsl.QuerydslPredicateArgumentResolver.resolveArgument(QuerydslPredicateArgumentResolver.java:125)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	... 107 more
```

---

**Affects:** 2.3.1 (Neumann SR1)

**Comment by erizzo** [comment]
This bug seems to make it impossible for an entity class to have any `get*()` methods that aren't mapped fields/properties. That includes so-called "derived" properties that don't have a persistent value directly, but are derived based on some calculation or logic.
I've tried annotating such method with `@Transient` and `@QueryType(PropertyType.NONE)` but neither makes any difference.
Seeing as such methods are standard idiom in Java (and other OO languages), this seems like a bug that would have been addressed sometime in the 2+ years it's been open. Is there any workaround other than choosing a different name for  methods (which is not always an option)?

**Comment by OrangeDog** [comment]
There's no easy workaround other than just patching it.

You can subclass `QuerydslPredicateArgumentResolver` and handle the exception in a different way, but it's already consumed the parameter at that point so it's tricky to get the expected behaviour.

**Comment by OrangeDog** [comment]
This issue is still present in 3.x but now a different exception is thrown:

```
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "field" is null
	at org.springframework.util.ReflectionUtils.getField(ReflectionUtils.java:672)
	at org.springframework.data.querydsl.binding.PropertyPathInformation.reifyPath(PropertyPathInformation.java:114)
	at org.springframework.data.querydsl.binding.PropertyPathInformation.reifyPath(PropertyPathInformation.java:101)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.lambda$getPath$0(QuerydslPredicateBuilder.java:164)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.lambda$getPath$1(QuerydslPredicateBuilder.java:164)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.getPath(QuerydslPredicateBuilder.java:164)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.invokeBinding(QuerydslPredicateBuilder.java:146)
	at org.springframework.data.querydsl.binding.QuerydslPredicateBuilder.getPredicate(QuerydslPredicateBuilder.java:115)
	at org.springframework.data.web.querydsl.QuerydslPredicateArgumentResolverSupport.getPredicate(QuerydslPredicateArgumentResolverSupport.java:107)
	at org.springframework.data.web.querydsl.QuerydslPredicateArgumentResolver.resolveArgument(QuerydslPredicateArgumentResolver.java:78)
        ...
```

**Comment by OrangeDog** [comment]
In 4.x it's back to an `IllegalArgumentException`.
