### ISSUE TITLE
Update CI to Java 16

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-commons#2334]

**Comment by gregturn** [comment]
Java 16 fails...

```
[2021-03-24T22:13:55.029Z] [INFO] --- kotlin-maven-plugin:1.4.30:compile (compile) @ spring-data-commons ---

[2021-03-24T22:13:56.396Z] [ERROR] java.lang.ExceptionInInitializerError

[2021-03-24T22:13:56.396Z] 	at com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:25)

[2021-03-24T22:13:56.396Z] 	at com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)

[2021-03-24T22:13:56.396Z] 	at com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.<init>(KotlinCoreEnvironment.kt:121)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:425)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:226)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execCompiler(KotlinCompileMojoBase.java:228)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:237)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:55)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execute(KotlinCompileMojoBase.java:209)

[2021-03-24T22:13:56.396Z] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execute(K2JVMCompileMojo.java:222)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)

[2021-03-24T22:13:56.396Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-03-24T22:13:56.396Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)

[2021-03-24T22:13:56.396Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-03-24T22:13:56.396Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)

[2021-03-24T22:13:56.396Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)

[2021-03-24T22:13:56.396Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)

[2021-03-24T22:13:56.396Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

[2021-03-24T22:13:56.396Z] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[2021-03-24T22:13:56.396Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-03-24T22:13:56.396Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)

[2021-03-24T22:13:56.396Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-03-24T22:13:56.396Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)

[2021-03-24T22:13:56.396Z] 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)

[2021-03-24T22:13:56.396Z] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @16bbaab3

[2021-03-24T22:13:56.396Z] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

[2021-03-24T22:13:56.396Z] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

[2021-03-24T22:13:56.396Z] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

[2021-03-24T22:13:56.396Z] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

[2021-03-24T22:13:56.396Z] 	at com.intellij.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:252)

[2021-03-24T22:13:56.396Z] 	at com.intellij.util.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:269)

[2021-03-24T22:13:56.396Z] 	at com.intellij.DynamicBundle.<clinit>(DynamicBundle.java:22)

[2021-03-24T22:13:56.396Z] 	... 46 more

```

**Comment by gregturn** [comment]
@sdeleuze What's your knowledge of Kotlin working with Java 16?

**Comment by sdeleuze** [comment]
Kotlin 1.4 does not support Java 16, Kotlin 1.5 to be released shortly will. Spring Boot 2.5 and related Spring Framework version will use Kotlin 1.5.
