### ISSUE TITLE
java.lang.InstantiationError after upgrading to Spring Boot 2.4.4 (spring data commons 2.4.6)

### ISSUE THREAD

**Issue by svpr3m0** [spring-projects/spring-data-commons#2340]
In a Spring Boot application we use Spring Data Mongo to map some documents. Some of them have embedded documents with a hierarchy, e.g.:

```
@Document("projects")
@TypeAlias("project")
data class Project(
       ...
       val budget: ProjectBudget)
```

```
abstract class ProjectBudget {

    abstract fun getCurrentBudget(): MonetaryAmount?

}
```
```
@TypeAlias("projectProjectBudget")
class ClosedProjectBudget(... ) : ProjectBudget() {}
```

Up to Spring Boot 2.4.3 when retrieving a Project instance the corresponding ProjectBudget subclass what built correctly. However after the upgrade to Boot 2.4.4 we get this exception:

```
Caused by: java.lang.InstantiationError: xxx.ProjectBudget
	at xxx.ProjectBudget_Instantiator_srp3na.newInstance(Unknown Source)
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:238)
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:87)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:344)

```

There seems to be a regression when instantiating subclasses.

**Comment by mp911de** [comment]
This looks actually as if the subclass isn't registered with MappingContext. To properly resolve the target class using TypeAlias, it must be already present in the context. 

Can you isolate the issue and provide a minimal reproducer?

**Comment by codependent** [comment]
Hi @mp911de, I've uploaded a sample project where you can reproduce the issue: https://github.com/codependent/mongo-sample2

The instructions are in the [readme file](https://github.com/codependent/mongo-sample2/blob/master/README.md).

**Comment by mp911de** [comment]
`ServiceProjectBudget` and `ProjectProjectBudget` are not annotated with `@Document` hence these types aren't discovered during the application startup.

**Comment by codependent** [comment]
@mp911de thanks for the suggestion, it solved the problem. What's funny is that with Spring Boot <=2.4.3 it was working without the annotations. Maybe it would be worth mentioning it in the docs.

**Comment by mp911de** [comment]
That's interesting. I'm not sure why this is. Since Spring Boot does the entity scan, it's worth raising an issue there.

**Comment by wilkinsona** [comment]
The Spring Boot 2.4.4-based sample works fine if I downgrade Spring Data to 2020.0.5 (the version used in Spring Boot 2.4.3). If I change the sample to be Spring Boot 2.4.3-based but with Spring Data upgraded to 2020.0.6 then the sample no longer works. As far as I can tell, it's something in Spring Data 2020.0.6 that's causing the problem.

**Comment by mp911de** [comment]
Let me have another look why this is.
