### ISSUE TITLE
Improve error messages if a repository cannot be created

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2341]
**[Tera](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49634)** opened **[DATACMNS-1812](https://jira.spring.io/browse/DATACMNS-1812?redirect=false)** and commented

I'm trying to use Spring data JDBC with Query DSL in Kotlin. This is my repository

 

```java
@Repository
interface AgentRepository : PagingAndSortingRepository<Agent, Int>, QuerydslPredicateExecutor<Agent> {}
```

I've integrated these dependencies in my Gradle build:

```java
implementation 'org.springframework.boot:spring-boot-starter-data-jdbc:2.3.3'
implementation("com.querydsl:querydsl-core:4.4.0") 
kapt "com.querydsl:querydsl-apt:4.4.0:jpa"
```

As soon as I try to start my application I get this error:

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentRepository' defined in it.dove.braniac.repositories.AgentRepository defined in @EnableJdbcRepositories declared on BraniacApplication: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract long org.springframework.data.querydsl.QuerydslPredicateExecutor.count(com.querydsl.core.types.Predicate)! Reason: No property count found for type Agent!
```

I can't understand what I'm doing wrong and if there is an incompatibility between Spring Data JDBC and QueryDSL

 

The same issue happens if I try to change from PagingAndSortingRepository to simple CrudRepository

---

**Affects:** 2.3.4 (Neumann SR4)

**Comment by mp911de** [comment]
Moving to Spring Data Commons.

**Comment by mp911de** [comment]
An error message would look like:

```
Caused by: java.lang.IllegalStateException: Repository com.example.jdbcquerybyexample.DemoApplication$PersonRepository implements org.springframework.data.repository.query.QueryByExampleExecutor but JdbcRepositoryFactory does not support Query by Example!
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$RepositoryValidator.validate(RepositoryFactorySupport.java:773) ~[spring-data-commons-2.5.0-GH-2341-SNAPSHOT.jar:2.5.0-GH-2341-SNAPSHOT]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.validate(RepositoryFactorySupport.java:507) ~[spring-data-commons-2.5.0-GH-2341-SNAPSHOT.jar:2.5.0-GH-2341-SNAPSHOT]
```
