### ISSUE TITLE
v2.7.3 - save() not working as expected for updates 

### ISSUE THREAD

**Issue by sagarikamraj** [spring-projects/spring-data-commons#2767]
I have recently upgraded my project to java 17 and spring boot 2.7.4 and spring cloud 2021.0.4. I am using mavenBom for spring cloud dependency management. It has brought in spring-data-commons-2.7.3.

With the upgrade, the CRUD repository's save() doesn't seem to be updating the existing objects. I am getting a duplicate key exception. (org.springframework.dao.DuplicateKeyException: Document with the given id already exists). I have already tried enabling transaction management, but to no avail.

Could you please help.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by sagarikamraj** [comment]
I am using spring-data with Couchbase as the DB. 
My custom repository interface extends org.springframework.data.repository.CrudRepository.
I have noticed that the upsert isn't working when using save(). 

My custom update method looks as below: 
Step 1 - get the ID from user
Step 2 - check if a doc exists in the DB with the given ID
Step 3 - if ID doesn't exist, create new doc in DB. 
If ID exists, get the existing doc from DB, update it and save in DB 

Problem: 
Step 3 mentioned above isn't working for update operations. The save() operation is failing with DuplicateKeyException. 
Please see the stack trace below

`stacktrace=org.springframework.dao.DuplicateKeyException: Document with the given id already exists {"completed":true,"coreId":"0x178e7df000000001","idempotent":false,"lastChannelId":"178E7DF000000001/000000007D798881","lastDispatchedFrom":"127.0.0.1:58740","lastDispatchedTo":"localhost:58656","requestId":25,"requestType":"InsertRequest","retried":0,"service":{"bucket":"test_bucket","collection":"_default","documentId":"2f0bed70-9cd9-4214-b99d-83bcb26f97aa","errorCode":{"description":"key already exists, or CAS mismatch","name":"KEY_EEXISTS"},"opaque":"0x25","scope":"_default","type":"kv","vbucket":639},"status":"EXISTS","timeoutMs":2500,"timings":{"dispatchMicros":23894,"encodingMicros":726,"totalDispatchMicros":23894,"totalServerMicros":0,"totalMicros":31835,"serverMicros":0}}; nested exception is com.couchbase.client.core.error.DocumentExistsException: Document with the given id already exists {"completed":true,"coreId":"0x178e7df000000001","idempotent":false,"lastChannelId":"178E7DF000000001/000000007D798881","lastDispatchedFrom":"127.0.0.1:58740","lastDispatchedTo":"localhost:58656","requestId":25,"requestType":"InsertRequest","retried":0,"service":{"bucket":"test_bucket","collection":"_default","documentId":"2f0bed70-9cd9-4214-b99d-83bcb26f97aa","errorCode":{"description":"key already exists, or CAS mismatch","name":"KEY_EEXISTS"},"opaque":"0x25","scope":"_default","type":"kv","vbucket":639},"status":"EXISTS","timeoutMs":2500,"timings":{"dispatchMicros":23894,"encodingMicros":726,"totalDispatchMicros":23894,"totalServerMicros":0,"totalMicros":31835,"serverMicros":0}}
	at org.springframework.data.couchbase.core.CouchbaseExceptionTranslator.translateExceptionIfPossible(CouchbaseExceptionTranslator.java:63)
	at org.springframework.data.couchbase.core.ReactiveCouchbaseTemplate.potentiallyConvertRuntimeException(ReactiveCouchbaseTemplate.java:169)
	at org.springframework.data.couchbase.core.ReactiveInsertByIdOperationSupport$ReactiveInsertByIdSupport.lambda$one$3(ReactiveInsertByIdOperationSupport.java:92)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)`

**Comment by sagarikamraj** [comment]
My data model looks like below:

`@Document(expiry = 7, expiryUnit = TimeUnit.DAYS, touchOnRead = true)

public class MyModel extends BaseModel {

  @Id @Field @NotNull private String uniqueId;

  @Field private Integer loadPlanVersion;

  @Version private Long documentVersion;

  @Field @NotNull private String someId;
}`


My repository class looks like this: 
`public interface MyRepository extends CrudRepository<MyModel, String> {
`
