### ISSUE TITLE
`QuerydslDefaultBinding` should unwrap nested collections for `IN` binding

### ISSUE THREAD

**Issue by rxxy** [spring-projects/spring-data-commons#2834]
when i bind the parameter on a property of type set

The predicate expected to be generated：
`id in sysUser.departments`

The actual generated predicate
`[id] in sysUser.departments`

This problem works fine in hibernate5, but throws an exception in hibernate6

```
2023-05-24 10:32:17.650 ERROR [http-nio-8083-exec-8]  at com.teamytd.config.web.UnknownExceptionNotice.commonException(UnknownExceptionNotice.java:32) - java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.lang.String (java.util.LinkedHashSet and java.lang.String are in module java.base of loader 'bootstrap')
	at org.hibernate.type.descriptor.java.StringJavaType.unwrap(StringJavaType.java:27)
	at org.hibernate.type.descriptor.jdbc.VarcharJdbcType$1.doBind(VarcharJdbcType.java:108)
	at org.hibernate.type.descriptor.jdbc.BasicBinder.bind(BasicBinder.java:61)
...
```

entity:
```
public class SysUser {
    ...
    private Set<SysDepartment> departments;
    ...
}
```

controller argument:
```
departments: 297e00ad8848850e0188488987d70013
```

![image](https://github.com/spring-projects/spring-data-commons/assets/14834156/3315b566-48a7-477d-8068-09ddcff74b93)
![image](https://github.com/spring-projects/spring-data-commons/assets/14834156/75b3315a-89ba-43dd-931d-a92c71d1f9eb)

**Comment by mp911de** [comment]
To help you to diagnose the problem, please spend some time providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by rxxy** [comment]
> To help you to diagnose the problem, please spend some time providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

see https://github.com/rxxy/springdatacommons-issue2834

**Comment by mp911de** [comment]
The HQL query is:

```
select sysUser
from SysUser sysUser
where (?1) member of sysUser.departments
```

The exception stack trace is:

```
java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.lang.Long (java.util.LinkedHashSet and java.lang.Long are in module java.base of loader 'bootstrap')
	at org.hibernate.type.descriptor.java.LongJavaType.unwrap(LongJavaType.java:24) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.type.descriptor.jdbc.BigIntJdbcType$1.doBind(BigIntJdbcType.java:62) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.type.descriptor.jdbc.BasicBinder.bind(BasicBinder.java:61) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:117) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.exec.internal.AbstractJdbcParameter.bindParameterValue(AbstractJdbcParameter.java:107) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.bindParameters(DeferredResultSetAccess.java:199) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:228) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:204) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:84) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:65) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:198) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:362) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:109) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:302) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:243) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.query.Query.getResultList(Query.java:119) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at com.querydsl.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:191) ~[querydsl-jpa-5.0.0-jakarta.jar:na]
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:243) ~[querydsl-jpa-5.0.0-jakarta.jar:na]
```

This is either a Querydsl or a Hibernate issue as the Querydsl code in Spring Data hasn't changed and Querydsl is creating the actual query.

**Comment by rxxy** [comment]
The parsed predicateis `[2] in sysUser.departments`
The correct predicateshould be `2 in sysUser.departments`

`[2] In sysUser.departments` should be a malformation, hibernate5.x is compatible with such a malformation.

I think it would be better to adjust to normal predicate, wouldn't it?

**Comment by rxxy** [comment]
select sysUser
from SysUser sysUser
where (?1) member of sysUser.departments

HQL is correct, but the parameter should be an entity object, not a Set

**Comment by mp911de** [comment]
`QuerydslPredicateBuilder` is able to convert `Foo,Bar` into a collection containing `Foo` and `Bar` elements. This also works for a single element that is wrapped into a collection-type. We should not break this behavior. 

It makes rather sense to unwrap nested collections in `QuerydslDefaultBinding` if a path is `CollectionPathBase`. Bindings can be overridden and we likely break less things that way.
