### ISSUE TITLE
Congestion in ClassTypeInformation

### ISSUE THREAD

**Issue by msevcenko** [spring-projects/spring-data-commons#2867]
In spring-data-commons:2.7, the ClassTypeInformation does not behave very well under heavy load.

One problem might be that it is implemented by weak reference tracking. Weak references are not appropriate for caching, they are wiped by gc at earliest convenience.

Another problem is, that computeIfAbsent, and even get, lock an entry in the cache.

Under heavy load, we ended up with dozens of threads locked in 

```
        at org.springframework.util.ConcurrentReferenceHashMap.put(ConcurrentReferenceHashMap.java:282)
        at org.springframework.util.ConcurrentReferenceHashMap.putIfAbsent(ConcurrentReferenceHashMap.java:277)
        at java.util.concurrent.ConcurrentMap.computeIfAbsent(java.base@11.0.10/ConcurrentMap.java:331)
        at org.springframework.data.util.ClassTypeInformation.from(ClassTypeInformation.java:73)
 ```

trying to compute evicted cache item. Possibly many threads trying to compute the same item?

a handful of them were also locked in:

```
        at org.springframework.util.ConcurrentReferenceHashMap$Segment.restructure(ConcurrentReferenceHashMap.java:582)
        at org.springframework.util.ConcurrentReferenceHashMap$Segment.restructureIfNecessary(ConcurrentReferenceHashMap.java:576)
        at org.springframework.util.ConcurrentReferenceHashMap$Segment.getReference(ConcurrentReferenceHashMap.java:495)
        at org.springframework.util.ConcurrentReferenceHashMap.getReference(ConcurrentReferenceHashMap.java:265)
        at org.springframework.util.ConcurrentReferenceHashMap.get(ConcurrentReferenceHashMap.java:235)
        at java.util.concurrent.ConcurrentMap.computeIfAbsent(java.base@11.0.10/ConcurrentMap.java:329)
        at org.springframework.data.util.ClassTypeInformation.from(ClassTypeInformation.java:73)
```

presumably because the reference was invalidated, so the map is trying to clean the invalid entry, also requiring cache entry lock.

Not sure how to improve this easily, but this proved as a big hotspot which completely killed our app.

**Comment by mp911de** [comment]
We replaced `ConcurrentReferenceHashMap` with `ConcurrentLruCache` in version 3.0. Values can easily get invalidated as converters obtain type information when mapping objects. After conversion, values are no longer being held.

For the 2.7 development line, there's nothing we can do without impacting the performance profile. Also, given that 2.7 is out for quite a while, changing the cache would impact a lot of existing applications.

**Comment by msevcenko** [comment]
Ah, thanks for info.

It is a no-issue, then.
