### ISSUE TITLE
Missing native-image reflection hint for org.springframework.data.domain.Unpaged?

### ISSUE THREAD

**Issue by mmoayyed** [spring-projects/spring-data-commons#3025]
# Environment

- Spring Data 3.2.2
- Spring Boot 3.2.1
- GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)

# Problem

It appears that `org.springframework.data.domain.Unpaged` needs a few native-image hints:

```
Caused by: java.lang.ExceptionInInitializerError: null
	at org.springframework.data.web.config.SpringDataJacksonConfiguration.pageModule(SpringDataJacksonConfiguration.java:46)
	at org.springframework.data.web.config.SpringDataJacksonConfiguration__BeanDefinitions.lambda$getPageModuleInstanceSupplier$1(SpringDataJacksonConfiguration__BeanDefinitions.java:46)
	at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63)
	at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$withGenerator$0(BeanInstanceSupplier.java:171)
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68)
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:206)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:218)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:206)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1216)
	... 134 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.data.domain.Unpaged]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:355)
	at org.springframework.data.web.config.SpringDataJacksonConfiguration$PageModule.<clinit>(SpringDataJacksonConfiguration.java:57)
	... 148 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.domain.Unpaged
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86)
	at java.base@21.0.1/java.lang.Class.forName(DynamicHub.java:1346)
	at java.base@21.0.1/java.lang.Class.forName(DynamicHub.java:1335)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:304)
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:345)
	... 149 common frames omitted
```

I suspect this is new in `3.2.2` as I think `3.2.1` did OK in this area.

Link to [GitHub Actions](https://github.com/mmoayyed/cas/actions/runs/7527371708/job/20487488405#step:9:379) job that showcases the failure.

**Comment by christophstrobl** [comment]
@mmoayyed thanks for reporting - we'll take care of that

**Comment by christophstrobl** [comment]
related to: #2987

**Comment by christophstrobl** [comment]
@mmoayyed snapshot builds for `3.2.x-3025-SNAPSHOT` should be available soon in case you wan't to give them a try.

**Comment by mmoayyed** [comment]
`3.2.x-3025-SNAPSHOT` removed the issue. Thank you!

**Comment by christophstrobl** [comment]
Thank you very much @mmoayyed for confirming the fix works!

**Comment by karlohrabar** [comment]
what's the solution then?
